
from sqlalchemy import create_engine, text
from app.core.config import settings

engine = create_engine(settings.DATABASE_URL)

with engine.connect() as conn:
    print("--- All Payments ---")
    results = conn.execute(text("SELECT id, amount, status, generated_by_id FROM payments")).fetchall()
    if not results:
        print("No payments found in the database.")
    for row in results:
        print(f"ID: {row[0]}, Amount: {row[1]}, Status: {row[2]}, Generated By: {row[3]}")
    
    print("\n--- All Verified Payments ---")
    results = conn.execute(text("SELECT id, amount, generated_by_id FROM payments WHERE status = 'VERIFIED'")).fetchall()
    for row in results:
        print(f"ID: {row[0]}, Amount: {row[1]}, Generated By: {row[2]}")
