"""add dual photos to visits

Revision ID: 0984295e7c47
Revises: c5572dfa633e
Create Date: 2026-03-18 15:27:48.984093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0984295e7c47'
down_revision: Union[str, Sequence[str], None] = 'c5572dfa633e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    #op.drop_index(op.f('ix_attendance_is_deleted'), table_name='attendance')
    #op.drop_table('attendance')
    #op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    #op.drop_table('system_settings')
    #op.drop_column('employee_performances', 'is_deleted')
    #op.drop_column('incentive_slabs', 'is_deleted')
    #op.drop_column('incentive_slips', 'is_deleted')
    op.add_column('visits', sa.Column('storefront_photo_url', sa.String(), nullable=True))
    op.add_column('visits', sa.Column('selfie_photo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'selfie_photo_url')
    op.drop_column('visits', 'storefront_photo_url')
    op.add_column('incentive_slips', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('incentive_slabs', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('employee_performances', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.create_table('system_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feature_flags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('system_settings_pkey'))
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('punch_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('punch_out', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('attendance_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('attendance_pkey'))
    )
    op.create_index(op.f('ix_attendance_is_deleted'), 'attendance', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    # ### end Alembic commands ###
