# backend/alembic/versions/10351063a8da_add_softdeletemixin.py
"""Add SoftDeleteMixin

Revision ID: 10351063a8da
Revises: b2fb7edd1387
Create Date: 2026-03-10 14:49:31.247914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10351063a8da'
down_revision: Union[str, Sequence[str], None] = 'b2fb7edd1387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incentive_slabs', 'min_units',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('incentive_slabs', 'max_units',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('incentive_slabs', 'incentive_per_unit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('incentive_slabs', 'slab_bonus',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.drop_column('incentive_slabs', 'min_percentage')
    op.drop_column('incentive_slabs', 'amount_per_unit')
    op.add_column('salary_slips', sa.Column('incentive_amount', sa.Float(), nullable=True))
    op.add_column('salary_slips', sa.Column('total_earnings', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salary_slips', 'total_earnings')
    op.drop_column('salary_slips', 'incentive_amount')
    op.add_column('incentive_slabs', sa.Column('amount_per_unit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('incentive_slabs', sa.Column('min_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('incentive_slabs', 'slab_bonus',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('incentive_slabs', 'incentive_per_unit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('incentive_slabs', 'max_units',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    op.alter_column('incentive_slabs', 'min_units',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    # ### end Alembic commands ###
