"""Add source to Shop

Revision ID: 181a9bd69dd3
Revises: e3cf37371977
Create Date: 2026-02-27 14:14:17.768647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '181a9bd69dd3'
down_revision: Union[str, Sequence[str], None] = 'e3cf37371977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'source')
    # ### end Alembic commands ###
