"""add status and owner to shop

Revision ID: 2a03d8db8870
Revises: 7875cb344847
Create Date: 2026-02-27 17:06:01.789765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a03d8db8870'
down_revision: Union[str, Sequence[str], None] = '7875cb344847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the enum type manually in Postgres
    shop_status = sa.Enum('NEW', 'CONTACTED', 'MEETING_SET', 'CONVERTED', name='shopstatus')
    shop_status.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('status', shop_status, nullable=True))
    op.add_column('shops', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_shops_status'), 'shops', ['status'], unique=False)
    op.create_foreign_key(None, 'shops', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shops', type_='foreignkey')
    op.drop_index(op.f('ix_shops_status'), table_name='shops')
    op.drop_column('shops', 'owner_id')
    op.drop_column('shops', 'status')
    # ### end Alembic commands ###
    
    # Drop the enum type
    sa.Enum(name='shopstatus').drop(op.get_bind(), checkfirst=True)
