# backend/alembic/versions/55c178d5c4c3_merge_employee_into_user.py
"""merge_employee_into_user

Revision ID: 55c178d5c4c3
Revises: 7703e9af892d
Create Date: 2026-03-03 14:39:32.597063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c178d5c4c3'
down_revision: Union[str, Sequence[str], None] = '7703e9af892d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Add new user_id columns to dependent tables
    op.add_column('employee_performances', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('incentive_slips', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('leave_records', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('salary_slips', sa.Column('user_id', sa.Integer(), nullable=True))

    # Step 2: Populate user_id from employee.user_id via a join
    op.execute("""
        UPDATE employee_performances ep
        SET user_id = e.user_id
        FROM employees e
        WHERE ep.employee_id = e.id
    """)
    op.execute("""
        UPDATE incentive_slips ins
        SET user_id = e.user_id
        FROM employees e
        WHERE ins.employee_id = e.id
    """)
    op.execute("""
        UPDATE leave_records lr
        SET user_id = e.user_id
        FROM employees e
        WHERE lr.employee_id = e.id
    """)
    op.execute("""
        UPDATE salary_slips ss
        SET user_id = e.user_id
        FROM employees e
        WHERE ss.employee_id = e.id
    """)

    # Step 3: Drop FK constraints pointing to employees table
    op.drop_constraint(op.f('employee_performances_employee_id_fkey'), 'employee_performances', type_='foreignkey')
    op.drop_constraint(op.f('incentive_slips_employee_id_fkey'), 'incentive_slips', type_='foreignkey')
    op.drop_constraint(op.f('leave_records_employee_id_fkey'), 'leave_records', type_='foreignkey')
    op.drop_constraint(op.f('salary_slips_employee_id_fkey'), 'salary_slips', type_='foreignkey')

    # Step 4: Drop employees table (no more FKs pointing to it)
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')

    # Step 5: Make user_id columns NOT NULL, create FK constraints to users
    op.alter_column('employee_performances', 'user_id', nullable=False)
    op.create_foreign_key(None, 'employee_performances', 'users', ['user_id'], ['id'])
    op.drop_column('employee_performances', 'employee_id')

    op.alter_column('incentive_slips', 'user_id', nullable=False)
    op.create_foreign_key(None, 'incentive_slips', 'users', ['user_id'], ['id'])
    op.drop_column('incentive_slips', 'employee_id')

    op.alter_column('leave_records', 'user_id', nullable=False)
    op.create_foreign_key(None, 'leave_records', 'users', ['user_id'], ['id'])
    op.drop_column('leave_records', 'employee_id')

    op.alter_column('salary_slips', 'user_id', nullable=False)
    op.create_foreign_key(None, 'salary_slips', 'users', ['user_id'], ['id'])
    op.drop_column('salary_slips', 'employee_id')

    # Step 6: Add HR columns to users table
    op.add_column('users', sa.Column('employee_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('joining_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('base_salary', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('target', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_employee_code'), 'users', ['employee_code'], unique=True)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_employee_code'), table_name='users')
    op.drop_column('users', 'department')
    op.drop_column('users', 'target')
    op.drop_column('users', 'base_salary')
    op.drop_column('users', 'joining_date')
    op.drop_column('users', 'employee_code')
    op.add_column('salary_slips', sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'salary_slips', type_='foreignkey')
    op.create_foreign_key(op.f('salary_slips_employee_id_fkey'), 'salary_slips', 'employees', ['employee_id'], ['id'])
    op.drop_column('salary_slips', 'user_id')
    op.add_column('leave_records', sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'leave_records', type_='foreignkey')
    op.create_foreign_key(op.f('leave_records_employee_id_fkey'), 'leave_records', 'employees', ['employee_id'], ['id'])
    op.drop_column('leave_records', 'user_id')
    op.add_column('incentive_slips', sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'incentive_slips', type_='foreignkey')
    op.create_foreign_key(op.f('incentive_slips_employee_id_fkey'), 'incentive_slips', 'employees', ['employee_id'], ['id'])
    op.drop_column('incentive_slips', 'user_id')
    op.add_column('employee_performances', sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employee_performances', type_='foreignkey')
    op.create_foreign_key(op.f('employee_performances_employee_id_fkey'), 'employee_performances', 'employees', ['employee_id'], ['id'])
    op.drop_column('employee_performances', 'user_id')
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('employee_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('joining_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('base_salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('target', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('employees_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('employees_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('employees_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=True)
    # ### end Alembic commands ###
