"""Add new features models

Revision ID: 5a860ba1d011
Revises: 7e0c071448c9
Create Date: 2026-02-19 18:35:01.010420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a860ba1d011'
down_revision: Union[str, Sequence[str], None] = '7e0c071448c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_slips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('generated_at', sa.Date(), nullable=True),
    sa.Column('base_salary', sa.Float(), nullable=False),
    sa.Column('paid_leaves', sa.Integer(), nullable=True),
    sa.Column('unpaid_leaves', sa.Integer(), nullable=True),
    sa.Column('deduction_amount', sa.Float(), nullable=True),
    sa.Column('final_salary', sa.Float(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_slips_id'), 'salary_slips', ['id'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'employee_id')
    )
    op.add_column('clients', sa.Column('referral_code', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('referred_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clients', 'users', ['referred_by_id'], ['id'])
    op.add_column('issues', sa.Column('assigned_to_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'issues', 'users', ['assigned_to_id'], ['id'])
    op.add_column('leave_records', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'leave_records', 'users', ['approved_by'], ['id'])
    
    # Create Enum type manually
    op.execute("CREATE TYPE meetingstatus AS ENUM ('SCHEDULED', 'COMPLETED', 'CANCELLED')")
    op.add_column('meeting_summaries', sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', name='meetingstatus'), nullable=True))
    op.add_column('meeting_summaries', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('referral_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_column('users', 'referral_code')
    op.drop_column('meeting_summaries', 'cancellation_reason')
    op.drop_column('meeting_summaries', 'status')
    op.execute("DROP TYPE meetingstatus")
    op.drop_constraint(None, 'leave_records', type_='foreignkey')
    op.drop_column('leave_records', 'approved_by')
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_column('issues', 'assigned_to_id')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'referred_by_id')
    op.drop_column('clients', 'referral_code')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_salary_slips_id'), table_name='salary_slips')
    op.drop_table('salary_slips')
    # ### end Alembic commands ###
