# backend/alembic/versions/6b1f364e6d19_add_assignment_status.py
"""add_assignment_status

Revision ID: 6b1f364e6d19
Revises: e01dad68ed4b
Create Date: 2026-03-10 16:28:54.608363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b1f364e6d19'
down_revision: Union[str, Sequence[str], None] = 'e01dad68ed4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('assignment_status', sa.String(), server_default='UNASSIGNED', nullable=False))
    op.add_column('shops', sa.Column('assignment_status', sa.String(), server_default='UNASSIGNED', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'assignment_status')
    op.drop_column('areas', 'assignment_status')
    # ### end Alembic commands ###
