# backend/alembic/versions/6c29239c47b1_add_is_deleted_to_user.py
"""add_is_deleted_to_user

Revision ID: 6c29239c47b1
Revises: ad906d96669b
Create Date: 2026-03-02 16:29:18.801921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c29239c47b1'
down_revision: Union[str, Sequence[str], None] = 'ad906d96669b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###
