"""Add feedback and incentives models

Revision ID: 6da9cf5f3b9a
Revises: 5a860ba1d011
Create Date: 2026-02-19 18:37:46.699664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '6da9cf5f3b9a'
down_revision: Union[str, Sequence[str], None] = '5a860ba1d011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incentive_slabs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_percentage', sa.Float(), nullable=False),
    sa.Column('amount_per_unit', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incentive_slabs_id'), 'incentive_slabs', ['id'], unique=False)
    op.create_table('incentive_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'SALES', 'TELESALES', 'PROJECT_MANAGER', 'PROJECT_MANAGER_AND_SALES', 'CLIENT', name='userrole', create_type=False), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incentive_targets_id'), 'incentive_targets', ['id'], unique=False)
    op.create_table('employee_performances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('closed_units', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_performances_id'), 'employee_performances', ['id'], unique=False)
    op.create_table('incentive_slips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('achieved', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('applied_slab', sa.Float(), nullable=True),
    sa.Column('amount_per_unit', sa.Float(), nullable=True),
    sa.Column('total_incentive', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incentive_slips_id'), 'incentive_slips', ['id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_id'), 'feedbacks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedbacks_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_incentive_slips_id'), table_name='incentive_slips')
    op.drop_table('incentive_slips')
    op.drop_index(op.f('ix_employee_performances_id'), table_name='employee_performances')
    op.drop_table('employee_performances')
    op.drop_index(op.f('ix_incentive_targets_id'), table_name='incentive_targets')
    op.drop_table('incentive_targets')
    op.drop_index(op.f('ix_incentive_slabs_id'), table_name='incentive_slabs')
    op.drop_table('incentive_slabs')
    # ### end Alembic commands ###
