"""Add advanced area targeting fields

Revision ID: 70a3857ef2c2
Revises: 7dc756e93ac9
Create Date: 2026-03-08 15:12:14.715129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70a3857ef2c2'
down_revision: Union[str, Sequence[str], None] = '7dc756e93ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('radius_meters', sa.Integer(), server_default='500', nullable=False))
    op.add_column('areas', sa.Column('shop_limit', sa.Integer(), server_default='20', nullable=False))
    op.add_column('areas', sa.Column('priority_level', sa.String(), server_default='MEDIUM', nullable=False))
    op.add_column('areas', sa.Column('auto_discovery_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('areas', sa.Column('target_categories', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('areas', 'target_categories')
    op.drop_column('areas', 'auto_discovery_enabled')
    op.drop_column('areas', 'priority_level')
    op.drop_column('areas', 'shop_limit')
    op.drop_column('areas', 'radius_meters')
    # ### end Alembic commands ###
