# backend/alembic/versions/7703e9af892d_add_timetable_and_update_todo_tables.py
"""Add timetable and update todo tables

Revision ID: 7703e9af892d
Revises: 6c29239c47b1
Create Date: 2026-03-02 18:41:27.275819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '7703e9af892d'
down_revision: Union[str, Sequence[str], None] = '6c29239c47b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    todopriority = postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='todopriority')
    todopriority.create(op.get_bind(), checkfirst=True)
    
    op.create_table('timetable_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('assignee_name', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_events_id'), 'timetable_events', ['id'], unique=False)
    op.add_column('todos', sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='todopriority'), nullable=True))
    op.add_column('todos', sa.Column('assigned_to', sa.String(), nullable=True))
    op.add_column('todos', sa.Column('related_entity', sa.String(), nullable=True))
    op.add_column('todos', sa.Column('evidence_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'evidence_url')
    op.drop_column('todos', 'related_entity')
    op.drop_column('todos', 'assigned_to')
    op.drop_column('todos', 'priority')
    op.drop_index(op.f('ix_timetable_events_id'), table_name='timetable_events')
    op.drop_table('timetable_events')

    todopriority = postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='todopriority')
    todopriority.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
