"""Add remarks and opened_at to Issue

Revision ID: 7875cb344847
Revises: ea22a7eaafe3
Create Date: 2026-02-27 14:59:56.084016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7875cb344847'
down_revision: Union[str, Sequence[str], None] = 'ea22a7eaafe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('issues', sa.Column('opened_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'opened_at')
    op.drop_column('issues', 'remarks')
    # ### end Alembic commands ###
