"""add demo metadata columns

Revision ID: 7b8a33af3101
Revises: 89b9b29e8764
Create Date: 2026-03-14 09:47:24.576674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b8a33af3101'
down_revision: Union[str, Sequence[str], None] = '89b9b29e8764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_table('attendance')
    op.alter_column('bills', 'payment_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'PERSONAL_ACCOUNT'::character varying"))
    op.alter_column('bills', 'gst_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'WITH_GST'::character varying"))
    op.alter_column('bills', 'invoice_series',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'INV'::character varying"))
    op.alter_column('bills', 'invoice_sequence',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('bills', 'requires_qr',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.add_column('shops', sa.Column('demo_title', sa.String(), nullable=True))
    op.add_column('shops', sa.Column('demo_type', sa.String(), nullable=True))
    op.add_column('shops', sa.Column('demo_notes', sa.Text(), nullable=True))
    op.add_column('shops', sa.Column('demo_meet_link', sa.String(), nullable=True))
    op.drop_constraint(op.f('fk_shops_project_manager_id_users'), 'shops', type_='foreignkey')
    op.create_foreign_key(None, 'shops', 'users', ['project_manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shops', type_='foreignkey')
    op.create_foreign_key(op.f('fk_shops_project_manager_id_users'), 'shops', 'users', ['project_manager_id'], ['id'], ondelete='SET NULL')
    op.drop_column('shops', 'demo_meet_link')
    op.drop_column('shops', 'demo_notes')
    op.drop_column('shops', 'demo_type')
    op.drop_column('shops', 'demo_title')
    op.alter_column('bills', 'requires_qr',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('bills', 'invoice_sequence',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('bills', 'invoice_series',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'INV'::character varying"))
    op.alter_column('bills', 'gst_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'WITH_GST'::character varying"))
    op.alter_column('bills', 'payment_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'PERSONAL_ACCOUNT'::character varying"))
    op.create_table('attendance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('punch_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('punch_out', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('attendance_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('attendance_pkey'))
    )
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feature_flags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('system_settings_pkey'))
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    # ### end Alembic commands ###
