"""alter applied_slab to string

Revision ID: 849e67921f01
Revises: 0e7917045276
Create Date: 2026-03-12 16:46:30.977016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '849e67921f01'
down_revision: Union[str, Sequence[str], None] = '0e7917045276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incentive_targets_id'), table_name='incentive_targets')
    op.drop_table('incentive_targets')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.alter_column('bills', 'invoice_client_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bills', 'invoice_client_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incentive_slips', 'applied_slab',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('salary_slips', sa.Column('slab_bonus', sa.Float(), nullable=True))
    op.add_column('salary_slips', sa.Column('status', sa.String(), server_default='CONFIRMED', nullable=False))
    op.add_column('salary_slips', sa.Column('confirmed_by', sa.Integer(), nullable=True))
    op.add_column('salary_slips', sa.Column('confirmed_at', sa.Date(), nullable=True))
    op.create_foreign_key(None, 'salary_slips', 'users', ['confirmed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'salary_slips', type_='foreignkey')
    op.drop_column('salary_slips', 'confirmed_at')
    op.drop_column('salary_slips', 'confirmed_by')
    op.drop_column('salary_slips', 'status')
    op.drop_column('salary_slips', 'slab_bonus')
    op.alter_column('incentive_slips', 'applied_slab',
               existing_type=sa.String(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('bills', 'invoice_client_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bills', 'invoice_client_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('system_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feature_flags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('system_settings_pkey'))
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('punch_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('punch_out', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('attendance_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('attendance_pkey'))
    )
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_table('incentive_targets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'SALES', 'TELESALES', 'PROJECT_MANAGER', 'PROJECT_MANAGER_AND_SALES', 'CLIENT', name='userrole'), autoincrement=False, nullable=False),
    sa.Column('period', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('incentive_targets_pkey'))
    )
    op.create_index(op.f('ix_incentive_targets_id'), 'incentive_targets', ['id'], unique=False)
    # ### end Alembic commands ###
