"""refactor_cleanups

Revision ID: 874bf8791884
Revises: bc9a9d3bb759
Create Date: 2026-02-23 11:56:07.092374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '874bf8791884'
down_revision: Union[str, Sequence[str], None] = 'bc9a9d3bb759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('TRUNCATE TABLE issues, meeting_summaries, visits, feedbacks CASCADE')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_pm_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('pm_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['pm_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_pm_history_client_id'), 'client_pm_history', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_pm_history_id'), 'client_pm_history', ['id'], unique=False)
    op.create_index(op.f('ix_client_pm_history_pm_id'), 'client_pm_history', ['pm_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('qr_code_data', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'FAILED', name='paymentstatus'), nullable=True),
    sa.Column('generated_by_id', sa.Integer(), nullable=False),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)

    op.add_column('clients', sa.Column('pm_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('clients_lead_id_key'), 'clients', type_='unique')
    op.drop_constraint(op.f('clients_lead_id_fkey'), 'clients', type_='foreignkey')
    op.create_foreign_key(None, 'clients', 'users', ['pm_id'], ['id'])
    op.drop_column('clients', 'lead_id')

    op.drop_constraint(op.f('feedbacks_project_id_fkey'), 'feedbacks', type_='foreignkey')
    op.drop_column('feedbacks', 'project_id')
    op.add_column('issues', sa.Column('client_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('issues_project_id_fkey'), 'issues', type_='foreignkey')
    op.create_foreign_key(None, 'issues', 'clients', ['client_id'], ['id'])
    op.drop_column('issues', 'project_id')
    op.add_column('meeting_summaries', sa.Column('client_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('meeting_summaries_project_id_fkey'), 'meeting_summaries', type_='foreignkey')
    op.create_foreign_key(None, 'meeting_summaries', 'clients', ['client_id'], ['id'])
    op.drop_column('meeting_summaries', 'project_id')
    op.add_column('visits', sa.Column('shop_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('visits_lead_id_fkey'), 'visits', type_='foreignkey')
    op.create_foreign_key(None, 'visits', 'shops', ['shop_id'], ['id'])
    op.drop_column('visits', 'lead_id')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_name'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pm_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PLANNED', 'ONGOING', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='projectstatus'), server_default=sa.text("'PLANNED'::projectstatus"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('projects_client_id_fkey')),
    sa.ForeignKeyConstraint(['pm_id'], ['users.id'], name=op.f('projects_pm_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('projects_pkey'))
    )
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('NEW', 'CONTACTED', 'INTERESTED', 'CONVERTED', 'LOST', name='leadstatus'), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('area_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name=op.f('leads_area_id_fkey')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('leads_owner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('leads_pkey'))
    )
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=False)
    op.create_index(op.f('ix_leads_name'), 'leads', ['name'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('project_members_employee_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_members_project_id_fkey')),
    sa.PrimaryKeyConstraint('project_id', 'employee_id', name=op.f('project_members_pkey'))
    )

    op.add_column('visits', sa.Column('lead_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.create_foreign_key(op.f('visits_lead_id_fkey'), 'visits', 'leads', ['lead_id'], ['id'])
    op.drop_column('visits', 'shop_id')
    op.add_column('meeting_summaries', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'meeting_summaries', type_='foreignkey')
    op.create_foreign_key(op.f('meeting_summaries_project_id_fkey'), 'meeting_summaries', 'projects', ['project_id'], ['id'])
    op.drop_column('meeting_summaries', 'client_id')
    op.add_column('issues', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.create_foreign_key(op.f('issues_project_id_fkey'), 'issues', 'projects', ['project_id'], ['id'])
    op.drop_column('issues', 'client_id')
    op.add_column('feedbacks', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('feedbacks_project_id_fkey'), 'feedbacks', 'projects', ['project_id'], ['id'])
    op.alter_column('feedbacks', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('clients', sa.Column('lead_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.create_foreign_key(op.f('clients_lead_id_fkey'), 'clients', 'leads', ['lead_id'], ['id'])
    op.create_unique_constraint(op.f('clients_lead_id_key'), 'clients', ['lead_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('clients', 'pm_id')

    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_client_pm_history_pm_id'), table_name='client_pm_history')
    op.drop_index(op.f('ix_client_pm_history_id'), table_name='client_pm_history')
    op.drop_index(op.f('ix_client_pm_history_client_id'), table_name='client_pm_history')
    op.drop_table('client_pm_history')
    # ### end Alembic commands ###
