"""Add synchronization fields

Revision ID: 87c6b6f81a60
Revises: 8bd7e5f07255
Create Date: 2026-03-07 18:19:10.457269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87c6b6f81a60'
down_revision: Union[str, Sequence[str], None] = '8bd7e5f07255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_summaries', sa.Column('todo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'meeting_summaries', 'todos', ['todo_id'], ['id'])
    op.add_column('todos', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todos', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'client_id')
    op.drop_constraint(None, 'meeting_summaries', type_='foreignkey')
    op.drop_column('meeting_summaries', 'todo_id')
    # ### end Alembic commands ###
