# backend/alembic/versions/8bd7e5f07255_add_start_and_end_time_to_tasks.py
"""add start and end time to tasks

Revision ID: 8bd7e5f07255
Revises: 161f1bb97c1f
Create Date: 2026-03-07 11:58:36.339210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bd7e5f07255'
down_revision: Union[str, Sequence[str], None] = '161f1bb97c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('todos', sa.Column('end_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'end_time')
    op.drop_column('todos', 'start_time')
    # ### end Alembic commands ###
