"""make notification created_at timezone aware

Revision ID: a1d03e23043f
Revises: 161f1bb97c1f
Create Date: 2026-03-07 16:51:30.068681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1d03e23043f'
down_revision: Union[str, Sequence[str], None] = '161f1bb97c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_clients_phone'), table_name='clients')
    op.create_index(op.f('ix_clients_phone'), 'clients', ['phone'], unique=True)
    op.add_column('issues', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('issues', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('issues', 'updated_at')
    op.drop_column('issues', 'created_at')
    op.drop_index(op.f('ix_clients_phone'), table_name='clients')
    op.create_index(op.f('ix_clients_phone'), 'clients', ['phone'], unique=False)
    op.alter_column('clients', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
