"""add missing columns

Revision ID: a711487ea316
Revises: d2f1b6a9c3e4
Create Date: 2026-03-14 10:23:49.183018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a711487ea316'
down_revision: Union[str, Sequence[str], None] = 'd2f1b6a9c3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_assignments')
    op.drop_index(op.f('ix_incentive_targets_id'), table_name='incentive_targets')
    op.drop_table('incentive_targets')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_table('area_assignments')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_table('attendance')
    op.add_column('bills', sa.Column('invoice_client_name', sa.String(), nullable=False))
    op.add_column('bills', sa.Column('invoice_client_phone', sa.String(), nullable=False))
    op.add_column('bills', sa.Column('invoice_client_email', sa.String(), nullable=True))
    op.add_column('bills', sa.Column('invoice_client_address', sa.Text(), nullable=True))
    op.add_column('bills', sa.Column('invoice_client_org', sa.String(), nullable=True))
    op.add_column('bills', sa.Column('invoice_status', sa.String(), nullable=True))
    op.add_column('bills', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('bills', sa.Column('verified_by_id', sa.Integer(), nullable=True))
    op.add_column('bills', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.add_column('bills', sa.Column('service_description', sa.Text(), nullable=True))
    op.alter_column('bills', 'shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bills', 'payment_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'PERSONAL_ACCOUNT'::character varying"))
    op.alter_column('bills', 'gst_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'WITH_GST'::character varying"))
    op.alter_column('bills', 'invoice_series',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'INV'::character varying"))
    op.alter_column('bills', 'invoice_sequence',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('bills', 'requires_qr',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_foreign_key(None, 'bills', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'bills', 'users', ['verified_by_id'], ['id'])
    op.alter_column('incentive_slabs', 'min_units',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('incentive_slabs', 'max_units',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('incentive_slabs', 'incentive_per_unit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('incentive_slabs', 'slab_bonus',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.drop_column('incentive_slabs', 'min_percentage')
    op.drop_column('incentive_slabs', 'amount_per_unit')
    op.add_column('incentive_slips', sa.Column('slab_bonus_amount', sa.Float(), nullable=True))
    op.alter_column('incentive_slips', 'applied_slab',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('leave_records', sa.Column('leave_type', sa.String(), server_default='CASUAL', nullable=False))
    op.add_column('leave_records', sa.Column('day_type', sa.String(), server_default='FULL', nullable=False))
    op.add_column('leave_records', sa.Column('remarks', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'meeting_summaries', 'todos', ['todo_id'], ['id'])
    op.add_column('projects', sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='projectpriority'), nullable=True))
    op.add_column('salary_slips', sa.Column('incentive_amount', sa.Float(), nullable=True))
    op.add_column('salary_slips', sa.Column('slab_bonus', sa.Float(), nullable=True))
    op.add_column('salary_slips', sa.Column('total_earnings', sa.Float(), nullable=False))
    op.add_column('salary_slips', sa.Column('status', sa.String(), server_default='CONFIRMED', nullable=False))
    op.add_column('salary_slips', sa.Column('confirmed_by', sa.Integer(), nullable=True))
    op.add_column('salary_slips', sa.Column('confirmed_at', sa.Date(), nullable=True))
    op.create_foreign_key(None, 'salary_slips', 'users', ['confirmed_by'], ['id'])
    op.alter_column('users', 'incentive_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('visits', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('users', 'incentive_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'salary_slips', type_='foreignkey')
    op.drop_column('salary_slips', 'confirmed_at')
    op.drop_column('salary_slips', 'confirmed_by')
    op.drop_column('salary_slips', 'status')
    op.drop_column('salary_slips', 'total_earnings')
    op.drop_column('salary_slips', 'slab_bonus')
    op.drop_column('salary_slips', 'incentive_amount')
    op.drop_column('projects', 'priority')
    op.drop_constraint(None, 'meeting_summaries', type_='foreignkey')
    op.drop_column('leave_records', 'remarks')
    op.drop_column('leave_records', 'day_type')
    op.drop_column('leave_records', 'leave_type')
    op.alter_column('incentive_slips', 'applied_slab',
               existing_type=sa.String(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('incentive_slips', 'slab_bonus_amount')
    op.add_column('incentive_slabs', sa.Column('amount_per_unit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('incentive_slabs', sa.Column('min_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('incentive_slabs', 'slab_bonus',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('incentive_slabs', 'incentive_per_unit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('incentive_slabs', 'max_units',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    op.alter_column('incentive_slabs', 'min_units',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_constraint(None, 'bills', type_='foreignkey')
    op.drop_constraint(None, 'bills', type_='foreignkey')
    op.alter_column('bills', 'requires_qr',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('bills', 'invoice_sequence',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('bills', 'invoice_series',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'INV'::character varying"))
    op.alter_column('bills', 'gst_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'WITH_GST'::character varying"))
    op.alter_column('bills', 'payment_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'PERSONAL_ACCOUNT'::character varying"))
    op.alter_column('bills', 'shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('bills', 'service_description')
    op.drop_column('bills', 'verified_at')
    op.drop_column('bills', 'verified_by_id')
    op.drop_column('bills', 'created_by_id')
    op.drop_column('bills', 'invoice_status')
    op.drop_column('bills', 'invoice_client_org')
    op.drop_column('bills', 'invoice_client_address')
    op.drop_column('bills', 'invoice_client_email')
    op.drop_column('bills', 'invoice_client_phone')
    op.drop_column('bills', 'invoice_client_name')
    op.create_table('attendance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('punch_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('punch_out', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('attendance_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('attendance_pkey'))
    )
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_table('area_assignments',
    sa.Column('area_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name=op.f('area_assignments_area_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('area_assignments_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('area_id', 'user_id', name=op.f('area_assignments_pkey'))
    )
    op.create_table('system_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feature_flags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('system_settings_pkey'))
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_table('incentive_targets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'SALES', 'TELESALES', 'PROJECT_MANAGER', 'PROJECT_MANAGER_AND_SALES', 'CLIENT', name='userrole'), autoincrement=False, nullable=False),
    sa.Column('period', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('incentive_targets_pkey'))
    )
    op.create_index(op.f('ix_incentive_targets_id'), 'incentive_targets', ['id'], unique=False)
    op.create_table('shop_assignments',
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('shop_assignments_shop_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('shop_assignments_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shop_id', 'user_id', name=op.f('shop_assignments_pkey'))
    )
    # ### end Alembic commands ###
