# backend/alembic/versions/a975384b99f5_add_description_to_areas.py
"""add description to areas

Revision ID: a975384b99f5
Revises: f001_merge_heads
Create Date: 2026-03-03 12:26:45.343764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a975384b99f5'
down_revision: Union[str, Sequence[str], None] = 'f001_merge_heads'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('description', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('address', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('project_type', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('requirements', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'requirements')
    op.drop_column('clients', 'project_type')
    op.drop_column('clients', 'address')
    op.drop_column('areas', 'description')
    # ### end Alembic commands ###
