"""add_created_by_tracker

Revision ID: a979df1b8bee
Revises: d06b4984f057
Create Date: 2026-03-10 18:55:38.908371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a979df1b8bee'
down_revision: Union[str, Sequence[str], None] = 'd06b4984f057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.add_column('areas', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'areas', 'users', ['created_by_id'], ['id'])
    op.add_column('shops', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shops', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shops', type_='foreignkey')
    op.drop_column('shops', 'created_by_id')
    op.drop_constraint(None, 'areas', type_='foreignkey')
    op.drop_column('areas', 'created_by_id')
    op.create_table('system_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feature_flags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('system_settings_pkey'))
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    # ### end Alembic commands ###
