# backend/alembic/versions/ad906d96669b_add_area_project_type_and_requirements_.py
"""add area project_type and requirements to shop

Revision ID: ad906d96669b
Revises: 2a03d8db8870
Create Date: 2026-02-27 17:13:07.926555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad906d96669b'
down_revision: Union[str, Sequence[str], None] = '2a03d8db8870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('shops', sa.Column('project_type', sa.String(), nullable=True))
    op.add_column('shops', sa.Column('requirements', sa.Text(), nullable=True))

    # area_id may already exist from the nency branch migration (e63278477e40)
    # Use raw SQL with IF NOT EXISTS to safely skip if already present
    conn = op.get_bind()
    cols = [row[0] for row in conn.execute(sa.text("SELECT column_name FROM information_schema.columns WHERE table_name='shops'"))]
    if 'area_id' not in cols:
        op.add_column('shops', sa.Column('area_id', sa.Integer(), nullable=True))
        op.create_foreign_key(None, 'shops', 'areas', ['area_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shops', type_='foreignkey')
    op.drop_column('shops', 'area_id')
    op.drop_column('shops', 'requirements')
    op.drop_column('shops', 'project_type')
    # ### end Alembic commands ###
