"""add area project_type and requirements to shop

Revision ID: ad906d96669b
Revises: 2a03d8db8870
Create Date: 2026-02-27 17:13:07.926555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad906d96669b'
down_revision: Union[str, Sequence[str], None] = '2a03d8db8870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('project_type', sa.String(), nullable=True))
    op.add_column('shops', sa.Column('requirements', sa.Text(), nullable=True))
    op.add_column('shops', sa.Column('area_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shops', 'areas', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shops', type_='foreignkey')
    op.drop_column('shops', 'area_id')
    op.drop_column('shops', 'requirements')
    op.drop_column('shops', 'project_type')
    # ### end Alembic commands ###
