"""sync missing columns v4

Revision ID: bcc107a03b22
Revises: 93525ac9b4f1
Create Date: 2026-03-21 13:19:51.397160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bcc107a03b22'
down_revision: Union[str, Sequence[str], None] = '93525ac9b4f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.alter_column('areas', 'assignment_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'UNASSIGNED'::character varying"))
    op.alter_column('areas', 'radius_meters',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('500'))
    op.alter_column('areas', 'shop_limit',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('20'))
    op.alter_column('areas', 'priority_level',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'MEDIUM'::character varying"))
    op.alter_column('areas', 'auto_discovery_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('areas', 'target_categories',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('areas', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('areas_assigned_to_id_fkey'), 'areas', type_='foreignkey')
    op.drop_column('areas', 'assigned_to_id')
    op.drop_column('employee_performances', 'is_deleted')
    op.alter_column('incentive_slabs', 'min_units',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('incentive_slabs', 'max_units',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('incentive_slabs', 'incentive_per_unit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('incentive_slabs', 'slab_bonus',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.drop_column('incentive_slabs', 'is_deleted')
    op.drop_column('incentive_slips', 'is_deleted')
    op.alter_column('leave_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('leave_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('salary_slips', 'incentive_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('salary_slips', 'slab_bonus',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('shops', 'assignment_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'UNASSIGNED'::character varying"))
    op.drop_column('shops', 'assignment_log')
    op.alter_column('users', 'incentive_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'incentive_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.add_column('shops', sa.Column('assignment_log', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True))
    op.alter_column('shops', 'assignment_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'UNASSIGNED'::character varying"))
    op.alter_column('salary_slips', 'slab_bonus',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('salary_slips', 'incentive_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('leave_records', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('leave_records', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('incentive_slips', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('incentive_slabs', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.alter_column('incentive_slabs', 'slab_bonus',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('incentive_slabs', 'incentive_per_unit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('incentive_slabs', 'max_units',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    op.alter_column('incentive_slabs', 'min_units',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.add_column('employee_performances', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('areas', sa.Column('assigned_to_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('areas_assigned_to_id_fkey'), 'areas', 'users', ['assigned_to_id'], ['id'])
    op.alter_column('areas', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('areas', 'target_categories',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('areas', 'auto_discovery_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('areas', 'priority_level',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'MEDIUM'::character varying"))
    op.alter_column('areas', 'shop_limit',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('20'))
    op.alter_column('areas', 'radius_meters',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('500'))
    op.alter_column('areas', 'assignment_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'UNASSIGNED'::character varying"))
    op.create_table('system_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feature_flags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('access_policy', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('policy_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('system_settings_pkey'))
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    # ### end Alembic commands ###
