"""sync_shop_and_visit_models

Revision ID: c5572dfa633e
Revises: unified_status_pipeline
Create Date: 2026-03-18 11:58:17.391170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5572dfa633e'
down_revision: Union[str, Sequence[str], None] = 'unified_status_pipeline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_table('attendance')
    op.create_index(op.f('ix_areas_is_deleted'), 'areas', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_bills_is_deleted'), 'bills', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_clients_is_deleted'), 'clients', ['is_deleted'], unique=False)
    op.drop_column('employee_performances', 'is_deleted')
    op.create_index(op.f('ix_feedbacks_is_deleted'), 'feedbacks', ['is_deleted'], unique=False)
    op.drop_column('incentive_slabs', 'is_deleted')
    op.alter_column('incentive_slips', 'is_visible_to_employee',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('incentive_slips', 'is_deleted')
    op.create_index(op.f('ix_issues_is_deleted'), 'issues', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_leave_records_is_deleted'), 'leave_records', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_meeting_summaries_is_deleted'), 'meeting_summaries', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_notifications_is_deleted'), 'notifications', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_payments_is_deleted'), 'payments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_projects_is_deleted'), 'projects', ['is_deleted'], unique=False)
    op.alter_column('salary_slips', 'is_visible_to_employee',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_salary_slips_is_deleted'), 'salary_slips', ['is_deleted'], unique=False)
    op.drop_index(op.f('ix_shops_status'), table_name='shops')
    op.create_index(op.f('ix_shops_is_deleted'), 'shops', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_shops_pipeline_stage'), 'shops', ['pipeline_stage'], unique=False)
    #op.drop_constraint(op.f('fk_shops_archived_by_id'), 'shops', type_='foreignkey')
    op.drop_column('shops', 'archived_by_id')
    op.drop_column('shops', 'is_archived')
    op.create_index(op.f('ix_timetable_events_is_deleted'), 'timetable_events', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_todos_is_deleted'), 'todos', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_feedbacks_is_deleted'), 'user_feedbacks', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_feedbacks_is_deleted'), table_name='user_feedbacks')
    op.drop_index(op.f('ix_todos_is_deleted'), table_name='todos')
    op.drop_index(op.f('ix_timetable_events_is_deleted'), table_name='timetable_events')
    op.add_column('shops', sa.Column('is_archived', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('shops', sa.Column('archived_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_shops_archived_by_id'), 'shops', 'users', ['archived_by_id'], ['id'])
    op.drop_index(op.f('ix_shops_pipeline_stage'), table_name='shops')
    op.drop_index(op.f('ix_shops_is_deleted'), table_name='shops')
    op.create_index(op.f('ix_shops_status'), 'shops', ['pipeline_stage'], unique=False)
    op.drop_index(op.f('ix_salary_slips_is_deleted'), table_name='salary_slips')
    op.alter_column('salary_slips', 'is_visible_to_employee',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_projects_is_deleted'), table_name='projects')
    op.drop_index(op.f('ix_payments_is_deleted'), table_name='payments')
    op.drop_index(op.f('ix_notifications_is_deleted'), table_name='notifications')
    op.drop_index(op.f('ix_meeting_summaries_is_deleted'), table_name='meeting_summaries')
    op.drop_index(op.f('ix_leave_records_is_deleted'), table_name='leave_records')
    op.drop_index(op.f('ix_issues_is_deleted'), table_name='issues')
    op.add_column('incentive_slips', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.alter_column('incentive_slips', 'is_visible_to_employee',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.add_column('incentive_slabs', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_feedbacks_is_deleted'), table_name='feedbacks')
    op.add_column('employee_performances', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_clients_is_deleted'), table_name='clients')
    op.drop_index(op.f('ix_bills_is_deleted'), table_name='bills')
    op.drop_index(op.f('ix_areas_is_deleted'), table_name='areas')
    op.create_table('attendance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('punch_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('punch_out', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('attendance_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('attendance_pkey'))
    )
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feature_flags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('system_settings_pkey'))
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    # ### end Alembic commands ###
