# backend/alembic/versions/d06b4984f057_add_lead_tracking.py
"""add_lead_tracking

Revision ID: d06b4984f057
Revises: 6b1f364e6d19
Create Date: 2026-03-10 18:06:23.417102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd06b4984f057'
down_revision: Union[str, Sequence[str], None] = '6b1f364e6d19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.add_column('areas', sa.Column('assigned_by_id', sa.Integer(), nullable=True))
    op.add_column('areas', sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'areas', 'users', ['assigned_by_id'], ['id'])
    op.add_column('shops', sa.Column('assigned_by_id', sa.Integer(), nullable=True))
    op.add_column('shops', sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'shops', 'users', ['assigned_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shops', type_='foreignkey')
    op.drop_column('shops', 'accepted_at')
    op.drop_column('shops', 'assigned_by_id')
    op.drop_constraint(None, 'areas', type_='foreignkey')
    op.drop_column('areas', 'accepted_at')
    op.drop_column('areas', 'assigned_by_id')
    op.create_table('system_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feature_flags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('system_settings_pkey'))
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    # ### end Alembic commands ###
