# backend/alembic/versions/d148191278bc_add_reminder_sent_to_meetings.py
"""add_reminder_sent_to_meetings

Revision ID: d148191278bc
Revises: 7545b714043c
Create Date: 2026-03-05 15:27:16.239481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd148191278bc'
down_revision: Union[str, Sequence[str], None] = '7545b714043c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_summaries', sa.Column('reminder_sent', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting_summaries', 'reminder_sent')
    # ### end Alembic commands ###
