"""add_client_is_active

Revision ID: dda8de5153f6
Revises: 874bf8791884
Create Date: 2026-02-23 12:40:18.260113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda8de5153f6'
down_revision: Union[str, Sequence[str], None] = '874bf8791884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_clients_is_active'), 'clients', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_is_active'), table_name='clients')
    op.drop_column('clients', 'is_active')
    # ### end Alembic commands ###
