"""add_map_coords_and_area_id

Revision ID: e63278477e40
Revises: 181a9bd69dd3
Create Date: 2026-02-27 17:07:26.009288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e63278477e40'
down_revision: Union[str, Sequence[str], None] = '181a9bd69dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()

    # areas: lat/lng
    area_cols = [r[0] for r in conn.execute(sa.text("SELECT column_name FROM information_schema.columns WHERE table_name='areas'"))]
    if 'lat' not in area_cols:
        op.add_column('areas', sa.Column('lat', sa.Float(), nullable=True))
    if 'lng' not in area_cols:
        op.add_column('areas', sa.Column('lng', sa.Float(), nullable=True))

    # shops: area_id (may already exist from ad906d96669b branch)
    shop_cols = [r[0] for r in conn.execute(sa.text("SELECT column_name FROM information_schema.columns WHERE table_name='shops'"))]
    if 'area_id' not in shop_cols:
        op.add_column('shops', sa.Column('area_id', sa.Integer(), nullable=True))
        op.create_foreign_key(None, 'shops', 'areas', ['area_id'], ['id'])

    # visits: swap notes -> remarks
    visit_cols = [r[0] for r in conn.execute(sa.text("SELECT column_name FROM information_schema.columns WHERE table_name='visits'"))]
    if 'remarks' not in visit_cols:
        op.add_column('visits', sa.Column('remarks', sa.Text(), nullable=True))
    if 'notes' in visit_cols:
        op.drop_column('visits', 'notes')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('visits', 'remarks')
    op.drop_constraint(None, 'shops', type_='foreignkey')
    op.drop_column('shops', 'area_id')
    op.drop_column('areas', 'lng')
    op.drop_column('areas', 'lat')
    # ### end Alembic commands ###
