# backend/alembic/versions/ffe63d4dabcc_add_created_at_and_updated_at_to_issue.py
"""Add created_at and updated_at to Issue

Revision ID: ffe63d4dabcc
Revises: de08302e2cfc
Create Date: 2026-03-06 15:14:18.571498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffe63d4dabcc'
down_revision: Union[str, Sequence[str], None] = 'de08302e2cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('clients_phone_key'), 'clients', type_='unique')
    op.drop_index(op.f('ix_clients_phone'), table_name='clients')
    op.create_index(op.f('ix_clients_phone'), 'clients', ['phone'], unique=True)
    op.add_column('issues', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('issues', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'updated_at')
    op.drop_column('issues', 'created_at')
    op.drop_index(op.f('ix_clients_phone'), table_name='clients')
    op.create_index(op.f('ix_clients_phone'), 'clients', ['phone'], unique=False)
    op.create_unique_constraint(op.f('clients_phone_key'), 'clients', ['phone'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
